version: 2

jobs:
  python_2_7_15:
    shell: /bin/bash --login
    macos:
      xcode: '9.0'
    steps:
    - checkout
    - run: |
        brew update
        python --version
        sudo -H pip install --upgrade virtualenv
        brew install pyenv
        echo 'eval "$(pyenv init -)"' >> ~/.bash_profile
        source ~/.bash_profile
        pyenv install 2.7.15
        pyenv versions
        pyenv global 2.7.15
        python --version
    - run: python setup.py install
    - run: python setup.py test

  python_3_4_8:
    shell: /bin/bash --login
    macos:
      xcode: '9.0'
    steps:
    - checkout
    - run: |
        brew update
        python --version
        sudo -H pip install --upgrade virtualenv
        brew install pyenv
        echo 'eval "$(pyenv init -)"' >> ~/.bash_profile
        source ~/.bash_profile
        pyenv install 3.4.8
        pyenv versions
        pyenv global 3.4.8
        python --version
    - run: python setup.py install
    - run: python setup.py test

  python_3_5_5:
    shell: /bin/bash --login
    macos:
      xcode: '9.0'
    steps:
    - checkout
    - run: |
        brew update
        python --version
        sudo -H pip install --upgrade virtualenv
        brew install pyenv
        echo 'eval "$(pyenv init -)"' >> ~/.bash_profile
        source ~/.bash_profile
        pyenv install 3.5.5
        pyenv versions
        pyenv global 3.5.5
        python --version
    - run: python setup.py install
    - run: python setup.py test

  python_3_6_5:
    shell: /bin/bash --login
    macos:
      xcode: '9.0'
    steps:
    - checkout
    - run: |
        brew update
        python --version
        sudo -H pip install --upgrade virtualenv
        brew install pyenv
        echo 'eval "$(pyenv init -)"' >> ~/.bash_profile
        source ~/.bash_profile
        pyenv install 3.6.5
        pyenv versions
        pyenv global 3.6.5
        python --version
    - run: python setup.py install
    - run: python setup.py test

workflows:
  version: 2
  python_matrix_build:
    jobs:
      - python_2_7_15
      - python_3_4_8
      - python_3_5_5
      - python_3_6_5
